name: Release

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      # CF_API_KEY: ${{ secrets.CF_API_KEY }}
      # WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: Setup Environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release Job
        uses: BigWigsMods/packager@master
      # - name: Notify Discord
      #   if: success()
      #   uses: Netail/webhook-notifier@v1
      #   with:
      #     discord-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     color: 'info'
      #     title: 'New ElvUI ActionBarBuddy Released'
      #     text: 'ElvUI ActionBarBuddy version ${{ env.RELEASE_VERSION }} has been released.  You can use your wow addon client that can download from wago addons or curse to update.'
      #     fields: '[{"name": "Repository", "value": "${{ github.event.repository.name }}"}, {"name": "Version", "value": "${{ env.RELEASE_VERSION }}"}]'
          # footer: Addons by Repooc
          # timestamp: true
      - name: Notify Discord
        if: success()
        uses: repooc/djs-actions@my_changes
        with:
          id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          title: ${{ github.event.repository.name }} Version ${{ env.RELEASE_VERSION }} Released!
          description: ${{ github.event.repository.name }} version ${{ env.RELEASE_VERSION }} has been released!  You can use your wow addon client that can download from wago addons or curse to update.
          fields: '[{"name": "Repository", "value": "${{ github.event.repository.name }}", "inline": true}, {"name": "Version", "value": "${{ env.RELEASE_VERSION }}", "inline": true}]'
          footer: Addons by Repooc
          timestamp: true
