name: Release

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      CF_URL: https://www.curseforge.com/wow/addons/actionbar-buddy-elvui-plugin/
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      WAGO_URL: https://addons.wago.io/addons/actionbar-buddy-elvui-plugin
    steps:
      - name: Clone Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: Setup Environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release Job
        uses: BigWigsMods/packager@master
      - name: Notify Discord
        if: success()
        uses: repooc/djs-actions@my_changes
        with:
          id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          title: 'New *${{ github.event.repository.name }}* Version Released!'
          description: '[${{ github.event.sender.login }}](${{ github.event.sender.html_url }}) has released a new version of ${{ github.event.repository.name }}!

            If you use a wow addon client that can download from either wago addons or curse, then it is recommended that you use that to install/update the addon.  You can update how you see fit, even if you want to download manually and install it, go for it.  The can grab the addon from the links down below.'
          fields: '[{"name": "Released By:", "value": "[${{ github.event.sender.login }}](${{ github.event.sender.html_url }})", "inline": true}, {"name": "Issue Tracker:", "value": "[${{ github.event.repository.name }}](${{ github.event.repository.html_url }}/issues)", "inline": true}, {"name": "Version", "value": "${{ env.RELEASE_VERSION }}", "inline": true}, {"name": "Wago Addons", "value": "[Click Here](${{ env.WAGO_URL }})", "inline": true}, {"name": "Curseforge", "value": "[Click Here](${{ env.CF_URL }})", "inline": true}, {"name": "Changelog", "value": "[Click Here](${{ github.event.repository.html_url }}/CHANGELOG.txt)", "inline": true}]'
          footer: Addons by Repooc
          timestamp: true
      - name: Publish
        id: publish-to-discord
        uses: Crec0/announce-n-crosspost@v1
        if: success()
        with:
          bot-token: ${{ secrets.ANNOUNCER_BOT_TOKEN }}
          channel: ${{ secrets.DISCORD_NEWS_CHANNEL_ID }}
          content: |
            **${{ github.event.repository.name }}** version ${{ env.RELEASE_VERSION }} has been released!

            You can view the [CHANGELOG](${{ github.event.repository.html_url }}/CHANGELOG.txt) here!

            If you would like to support me in the work I do, consider supporting me through [Ko-Fi](https://ko-fi.com/repoocreforged), [Patreon](https://patreon.com/repoocreforged) or [Discord Shop](https://discord.com/servers/repooc-reforged-1162274244487561216)!

            Go grab the new version from [Wago AddOns](${{ env.WAGO_URL }}) or [Curse](${{ env.CF_URL }})!


      - name: Print message id
        run: echo "Message id = ${{ steps.publish-to-discord.outputs.message-id }}"

